### ISSUE TITLE
管理员账号登录不上

### ISSUE THREAD

**Issue by linhaotao168** [youshutong2080/shutongFlow#29]
请问我登录不上admin的这个账号是什么原因，其他普通账号也登不上

**Comment by blackholll** [comment]
初始sql没导入？  如果你不导入项目跟目录下的sql.你可以进入 apps目录下执行python manage.py createsuperuser来创建一个管理员用户

**Comment by linhaotao168** [comment]
有导入初始sql。也有执行python manage.py

**Comment by linhaotao168** [comment]
执行python manage.py createsuperuser来创建一个管理员用户出现报错
Traceback (most recent call last):
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1048, "Column 'alias' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 179, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/contrib/auth/models.py", line 161, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/contrib/auth/models.py", line 144, in _create_user
    user.save(using=self._db)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1284, in execute_sql
    cursor.execute(sql, params)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/data/virtualenv/loonflow/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    raise utils.IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'alias' cannot be null")

**Comment by blackholll** [comment]
你这是要登录loonflow的管理后台？  loonflow1.0 表结构做了调整，不支持shutongflow中的loonflow_init.sql.   loonflow本身提供了init.sql导入后 有admin用户 初始密码loonflow123

**Comment by linhaotao168** [comment]
我要登录shutongflow的前段，如你所说，我执行python manage.py createsuperuser来创建一个管理员用户出现的报错

**Comment by blackholll** [comment]
导入了shutongflow的sql的话， 可以使用readme中说明的的账号密码来登录，你导入失败了吧.   另外检查下数据库链接配置的是否正确

**Comment by linhaotao168** [comment]
应该导入成功了。用吧Navicat连接上去可以看到表了那些数据

**Comment by blackholll** [comment]
导入后shutongFlow中所有普通用户
'webb': asdasd，
'ops': asdasd，
'hr': asdasd，
'scm': asdasd，
'webb': asdasd，
'lilian': asdasd，
'david': asdasd
管理员为
'admin': yxuqtr
检查下下这些用户是否存在。   使用adimin登录后可以访问/admin页面创建用户。因为python manage.py createsuperuser默认不输入alias，而模型中这个字段必填了，所以直接执行这个命令无法创建用户， 你也可以修改下数据库里面吧这个字段设置为允许为空

**Comment by linhaotao168** [comment]
![image](https://user-images.githubusercontent.com/32661401/78320734-bc234f00-759c-11ea-8407-3643eeba6a50.png)

**Comment by linhaotao168** [comment]
![image](https://user-images.githubusercontent.com/32661401/78320751-c7767a80-759c-11ea-890f-87c6ee3de6a4.png)

**Comment by linhaotao168** [comment]
发现前端数据库  6062    不能打开

**Comment by blackholll** [comment]
前端数据库？？  6062是shutongflow后端用的端口

**Comment by linhaotao168** [comment]
[HPM] Error occurred while trying to proxy request /api/v1/account/obtain_token/ from 10.0.1.242:6061 to http://10.0.1.242:6062 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by blackholll** [comment]
shutongflow的后端没启动吧。 调用关系为:
shutongflow前端-->shutongflow后端---loonflow

**Comment by linhaotao168** [comment]
非常感谢你的耐心解答。问题找到了。shutongflow后端没启动
