### ISSUE TITLE
流程流转没有反应

### ISSUE THREAD

**Issue by RPCSS** [youshutong2080/shutongFlow#36]
配置好一个工作流程后，在第二步单击提交按钮进行流转进行第三步，但在shutongflow界面的待办列表里还是第二步，右上角却显示处理成功。在loonflow日志里发现：
2020-08-27 11:35:59,108 D:\Work\wf\loonflow\service\common\log_service.py process-12256 thread-1760 20 [ERROR]: Traceback (most recent call last):
  File "D:\Work\wf\loonflow\service\common\log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "D:\Work\wf\loonflow\service\ticket\ticket_base_service.py", line 1908, in get_ticket_state_participant_info
    if state_obj.type_id == constant_service_ins.STATE_TYPE_START:
AttributeError: 'str' object has no attribute 'type_id'
请问是哪里出了问题？

**Comment by blackholll** [comment]
检查下 提交这个操作 也就是流转 在工作配置里面， 流转的目标状态是不是已经被删除了

**Comment by RPCSS** [comment]
> 检查下 提交这个操作 也就是流转 在工作配置里面， 流转的目标状态是不是已经被删除了

没有，并且流程图能正常画出来

**Comment by RPCSS** [comment]
现在解决了，因为条件流转那里的target_state_id没有加引号
